pool:
  vmImage: 'ubuntu-16.04'

variables:
  ResourceGroupName: "UniTradicionalProject"
  prefix: "t"
  sqlAdminUsername: ""
  sqlAdminPassword: ""
  BuildConfiguration: 'Release'
  ingestionName: 'CatalogDatabase'

resources:
  repositories:
  - repository: UniTradicional
    type: git
    name: UniTradicional
    ref: master
  
stages:
  - stage: Build
    displayName: Build 
    jobs: 
    - job: 'UniTradicionalBuild'
      displayName: tradicional-build
      
      steps:
      - checkout: UniTradicional
      - task: AzurePowerShell@5
        displayName: 'Deploy data platform'
        inputs:
          azureSubscription: ''
          ScriptPath: 'UniTradicional/deployResources.ps1' 
          ScriptArguments: '-ResourceGroupName $(ResourceGroupName) -sqlAdminUsername $(sqlAdminUsername) -sqlAdminPassword $(sqlAdminPassword) -resourcePrefix $(prefix) '
          azurePowerShellVersion: LatestVersion
        enabled: true
            
      - task: DotNetCoreCLI@2
        displayName: 'Restore dependencies'
        inputs:
          command: 'restore'
          projects: 'UniTradicional/Functions/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build Function project'
        inputs:
          command: 'build'
          projects: 'UniTradicional/Functions/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Publish and zip'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'UniTradicional/Functions/Catalogo.csproj'
          arguments: ' --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/FunctionUniTradicional --no-build'
          zipAfterPublish: true
          modifyOutputPath: false
          
      - publish: '$(Build.ArtifactStagingDirectory)/UniTradicional'
        artifact: 'unitradional.function.$(Build.BuildNumber)'
      
      - task: AzureFunctionApp@1
        displayName: 'Azure Function App Deploy'
        inputs:
           azureSubscription: ''
           appType: functionApp
           appName: "$(functionName)"
           package: '$(Build.ArtifactStagingDirectory)/**/*.zip'


      
     
     

